/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjetoValvulasV8m31xRouteImport } from './routes/projeto-valvulas-v8m31x'
import { Route as IndexRouteImport } from './routes/index'

const ProjetoValvulasV8m31xRoute = ProjetoValvulasV8m31xRouteImport.update({
  id: '/projeto-valvulas-v8m31x',
  path: '/projeto-valvulas-v8m31x',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projeto-valvulas-v8m31x': typeof ProjetoValvulasV8m31xRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projeto-valvulas-v8m31x': typeof ProjetoValvulasV8m31xRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projeto-valvulas-v8m31x': typeof ProjetoValvulasV8m31xRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projeto-valvulas-v8m31x'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projeto-valvulas-v8m31x'
  id: '__root__' | '/' | '/projeto-valvulas-v8m31x'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjetoValvulasV8m31xRoute: typeof ProjetoValvulasV8m31xRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projeto-valvulas-v8m31x': {
      id: '/projeto-valvulas-v8m31x'
      path: '/projeto-valvulas-v8m31x'
      fullPath: '/projeto-valvulas-v8m31x'
      preLoaderRoute: typeof ProjetoValvulasV8m31xRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjetoValvulasV8m31xRoute: ProjetoValvulasV8m31xRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
